[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
cache = true
cache_path = "cache"
broadcast = "broadcast"
gas_reports = ["MToken", "MinterGateway"]
gas_reports_ignore = []
solc-version = "0.8.23"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 999999
verbosity = 3
ignored_error_codes = []
block_number = 19_812_380
block_timestamp = 1_715_029_200
build_info = true
sizes = true

[profile.default.fuzz]
runs = 5000

[profile.default.invariant]
runs = 512
depth = 25
fail_on_revert = true

[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
